server:
  port: 8080

spring:
  application:
    name: "rinhabueno"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank-db}
    username: ${DB_USER:rinha_user}
    password: ${DB_PASSWORD:my_rinha_password}


  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
