version: '3.9'

services:

  api01: &api
    image: rogerbu/rinhabueno:latest
    hostname: api01
    environment:
      - DB_URL=jdbc:postgresql://db:5432/rinha-db
      - DB_USER=rinha
      - DB_PASSWORD=rinha
      - THREADS=130
      - HIKARI_POOL_SIZE=90
      - HIKARI_POOL_MIN_IDLE=60
      - SERVER_PORT=8080
    ports:
      - "8080:9999"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "130MB"

  api02:
    <<: *api
    image: rogerbu/rinhabueno:latest
    hostname: api02
    ports:
      - "8081:9999"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rinha
      POSTGRES_USER: rinha
      POSTGRES_DB: rinha-db
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "270MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  default:
    driver: bridge
    name: rinha