version: '3.9'

services:

  api01: &api
    image: rogerbu/rinhabueno:latest
    hostname: api01
    environment:
      - DB_URL=jdbc:postgresql://db:5432/bank-db
      - DB_USER=rinha_user
      - DB_PASSWORD=my_rinha_password
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api02:
    <<: *api
    image: rogerbu/rinhabueno:latest
    hostname: api02
    ports:
      - "8081:8080"

  db:
    image: postgres:alpine
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: my_rinha_password
      POSTGRES_USER: rinha_user
      POSTGRES_DB: bank-db
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "140MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  default:
    driver: bridge
    name: rinha